import "./globals.css";
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],

})


export const metadata = {
  title: "Navigation List",
  description: "Generated by create next app - happily coded by Piotr Rutkowski",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
